const PRODUCTS = [
  {
    id: "RM001",
    name: "Mesh Makeup Travel Pouch",
    category: "accessories",
    categoryLabel: "Accessories",
    price: 59,
    oldPrice: null,
    rating: null,
    sold: null,
    image: "assets/images/mesh-pouch-01.jpg",
    fallbackEmoji: "👜",
    badge: "Pre-Order",
    preorder: true
  },
  {
    id: "RM002",
    name: "Mini Bluetooth Speaker",
    category: "gadgets",
    categoryLabel: "Gadgets",
    price: 199,
    oldPrice: 299,
    rating: 4.7,
    sold: 856,
    image: "assets/images/speaker-01.jpg",
    fallbackEmoji: "🔊",
    badge: "New",
    preorder: false
  },
  {
    id: "RM003",
    name: "Portable Storage Organizer",
    category: "home",
    categoryLabel: "Home",
    price: 129,
    oldPrice: 199,
    rating: 4.9,
    sold: 2400,
    image: "assets/images/organizer-01.jpg",
    fallbackEmoji: "🧺",
    badge: "Sale",
    preorder: false
  },
  {
    id: "RM004",
    name: "Travel Perfume Atomizer",
    category: "beauty",
    categoryLabel: "Beauty",
    price: 89,
    oldPrice: 149,
    rating: 4.8,
    sold: 3100,
    image: "assets/images/atomizer-01.jpg",
    fallbackEmoji: "🌸",
    badge: "Pick",
    preorder: false
  },
  {
    id: "RM005",
    name: "Minimal Crossbody Bag",
    category: "accessories",
    categoryLabel: "Accessories",
    price: 179,
    oldPrice: 249,
    rating: 4.6,
    sold: 740,
    image: "assets/images/crossbody-01.jpg",
    fallbackEmoji: "👜",
    badge: "Trend",
    preorder: false
  },
  {
    id: "RM006",
    name: "Wireless Mini Fan",
    category: "gadgets",
    categoryLabel: "Gadgets",
    price: 299,
    oldPrice: 399,
    rating: 4.7,
    sold: 965,
    image: "assets/images/mini-fan-01.jpg",
    fallbackEmoji: "🌀",
    badge: "Popular",
    preorder: false
  }
];
